#!/bin/bash
# generate-hot-files-list.sh — regenerates hot-files.list from install config (WP-450 S-50)
# Replaces the hand-maintained static list: rule files are auto-discovered by
# glob, the governance-repo CLAUDE.md is resolved via GOVERNANCE_REPO
# (the same config key setup.sh already writes to .exocortex.env for every
# fresh install — no new config surface, no hardcoded personal repo name).
set -euo pipefail

IWE_ROOT="${IWE_ROOT:-$HOME/IWE}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/hot-files.list"

GOVERNANCE_REPO="${IWE_GOVERNANCE_REPO:-DS-strategy}"
if [ -f "$IWE_ROOT/.exocortex.env" ]; then
  gov="$(grep -E '^GOVERNANCE_REPO=' "$IWE_ROOT/.exocortex.env" | tail -1 | cut -d= -f2-)"
  [ -n "$gov" ] && GOVERNANCE_REPO="$gov"
fi

{
  echo "# Auto-generated by generate-hot-files-list.sh — do not hand-edit, regenerate instead."
  # .claude/rules/*.md — every file auto-loaded by Claude Code, discovered by glob
  # (was 4 hardcoded filenames; a new rule file now appears here without list maintenance).
  find "$IWE_ROOT/.claude/rules" -maxdepth 1 -name "*.md" | sed "s|^$IWE_ROOT|\$IWE_ROOT|" | sort
  # Root CLAUDE.md — structural, every IWE install has exactly one.
  echo '$IWE_ROOT/CLAUDE.md'
  # Governance repo CLAUDE.md — resolved via GOVERNANCE_REPO, not hardcoded.
  if [ -f "$IWE_ROOT/$GOVERNANCE_REPO/CLAUDE.md" ]; then
    echo "\$IWE_ROOT/$GOVERNANCE_REPO/CLAUDE.md"
  fi
} > "$OUT"

echo "generate-hot-files-list: wrote $(grep -vc '^#' "$OUT") file(s) to $OUT (governance repo: $GOVERNANCE_REPO)"
