#!/bin/bash
# install-iwe-paths.sh — генерация workspace/.iwe-paths + sourcing из ~/.zshenv.
#
# Source-of-truth для IWE_* path-переменных (WP-219, DP.FM.009).
# Вызывается из:
#   - setup.sh (первичная установка)
#   - scripts/migrate-to-runtime-target.sh (миграция 0.28.x → 0.29.x)
#   - update.sh (повторная генерация после апгрейда — на случай если шаблон строки меняется)
#
# OwnerIntegrity: один файл — одно место. Раньше блок был дублирован в setup.sh [4d];
# при миграции ~/.iwe-paths не апгрейдился (Round 5 Евгения, 27 апр).
#
# Usage:
#   bash install-iwe-paths.sh --workspace PATH --governance REPO_NAME [--dry-run] [--quiet]
#
# Exit codes:
#   0 — успех
#   1 — некорректные аргументы

set -eu

WORKSPACE_DIR=""
GOVERNANCE_REPO=""
DRY_RUN=false
QUIET=false

while [ $# -gt 0 ]; do
    case "$1" in
        --workspace)  WORKSPACE_DIR="$2"; shift 2 ;;
        --governance) GOVERNANCE_REPO="$2"; shift 2 ;;
        --dry-run)    DRY_RUN=true; shift ;;
        --quiet|-q)   QUIET=true; shift ;;
        --help|-h)
            grep '^#' "$0" | head -20
            exit 0
            ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if [ -z "$WORKSPACE_DIR" ]; then
    echo "ERROR: --workspace обязателен" >&2
    exit 1
fi

WORKSPACE_DIR="${WORKSPACE_DIR/#\~/$HOME}"
GOVERNANCE_REPO="${GOVERNANCE_REPO:-DS-strategy}"

IWE_ENV_FILE="$WORKSPACE_DIR/.iwe-paths"
ZSHENV_FILE="$HOME/.zshenv"
IWE_ENV_MARKER="# IWE environment (WP-219, DP.FM.009): lookup-слой для путей к скриптам"

if $DRY_RUN; then
    $QUIET || echo "  [DRY RUN] Would write $IWE_ENV_FILE (workspace=$WORKSPACE_DIR, governance=$GOVERNANCE_REPO)"
    $QUIET || echo "  [DRY RUN] Would ensure $ZSHENV_FILE sources \$WORKSPACE_DIR/.iwe-paths"
    exit 0
fi

cat > "$IWE_ENV_FILE" <<IWEENV_EOF
# IWE environment variables
# Generated by install-iwe-paths.sh. Rerun setup.sh / migrate-to-runtime-target.sh / iwe-update to regenerate.
# Do not edit manually — changes will be lost.

export IWE_WORKSPACE="$WORKSPACE_DIR"
export IWE_TEMPLATE="\$IWE_WORKSPACE/FMT-exocortex-template"
export IWE_SCRIPTS="\$IWE_TEMPLATE/scripts"
export IWE_ROLES="\$IWE_TEMPLATE/roles"
export IWE_RUNTIME="\$IWE_WORKSPACE/.iwe-runtime"
export IWE_GOVERNANCE_REPO="$GOVERNANCE_REPO"
IWEENV_EOF

$QUIET || echo "  ✓ $IWE_ENV_FILE written (workspace=$WORKSPACE_DIR)"

# Replace both the legacy $HOME/.iwe-paths one-liner and any older managed
# block. Marker presence alone is not proof that it sources this workspace.
if [ -f "$ZSHENV_FILE" ]; then
    ZSHENV_TMP=$(mktemp)
    awk '
      /^# IWE environment \(WP-219, DP.FM.009\):/{skip=1; next}
      skip && /^unset _IWE_ROOT$/{skip=0; next}
      /\[ -f "\$HOME\/\.iwe-paths" \] && source "\$HOME\/\.iwe-paths"/{next}
      !skip{print}
    ' "$ZSHENV_FILE" > "$ZSHENV_TMP"
    mv "$ZSHENV_TMP" "$ZSHENV_FILE"
fi
if ! grep -qF "_IWE_ROOT=\"$WORKSPACE_DIR\"" "$ZSHENV_FILE" 2>/dev/null; then
    cat >> "$ZSHENV_FILE" <<ZSHENV_EOF

# IWE environment (WP-219, DP.FM.009): lookup-слой для путей к скриптам
_IWE_ROOT="$WORKSPACE_DIR"
[ -f "\$_IWE_ROOT/.iwe-paths" ] && source "\$_IWE_ROOT/.iwe-paths"
unset _IWE_ROOT
ZSHENV_EOF
    $QUIET || echo "  ✓ $ZSHENV_FILE → sources \$WORKSPACE_DIR/.iwe-paths"
else
    $QUIET || echo "  ○ $ZSHENV_FILE already sources $WORKSPACE_DIR/.iwe-paths"
fi

# Auto-enable pre-commit hooks for IWE repos that have .githooks/
# (Claude peer-review, 2026-05-26 — BFS3)
for repo_dir in "$WORKSPACE_DIR"/* "$WORKSPACE_DIR"/*/*; do
    [ -d "$repo_dir/.git" ] || continue
    [ -d "$repo_dir/.githooks" ] || continue
    if [ "$(git -C "$repo_dir" config --local core.hooksPath 2>/dev/null)" != ".githooks" ]; then
        git -C "$repo_dir" config --local core.hooksPath .githooks
        $QUIET || echo "  ✓ $repo_dir → core.hooksPath=.githooks"
    fi
done
